### ISSUE TITLE
Build a GitBook with content of this repository

### ISSUE THREAD

**Issue by woliveiras** [daliannyvieira/css-animations-pocket-guide#4]
It would be very nice if this project were a GitBook!

GitBook is easy to create a simple book with your repository.

Look this example: https://woliveiras.com.br/vimparanoobs/

Motivation for me: https://github.com/woliveiras/vimparanoobs/issues/1

My repository: https://github.com/woliveiras/vimparanoobs

GitBook: https://github.com/GitbookIO/gitbook

**Comment by daliannyvieira** [comment]
Show! vou providenciar isso! xD

**Comment by woliveiras** [comment]
Opa, eu escrevi em inglês por costume. Se pode ser em pt-br, melhor ainda pra mim! kkkk

Se precisar de ajuda é só dar um toque. :raised_hands:

**Comment by daliannyvieira** [comment]
@woliveiras meses depois consegui! Depois dá uma olhada! Obrigadão pelas contribuições e incentivo 
https://daliannyvieira.gitbooks.io/css-animations-pocket-guide/

**Comment by woliveiras** [comment]
Shoooooow!!!

Vamos fechar a issue então. Sucesssssso!
