### ISSUE TITLE
Escolher uma licença

### ISSUE THREAD

**Issue by afonsopacifer** [daliannyvieira/css-animations-pocket-guide#5]
O que você acha de adicionar uma licença ao projeto?

É algo bem importante, ainda mais para um projeto que vai bombar como esse ;)

Para facilitar a escolha você pode dar uma olhada nesse projeto [escolhaumalicenca](http://escolhaumalicenca.com.br/)

**Comment by daliannyvieira** [comment]
Muito obrigada pela sugestão e pelo link! Vou adicionar uma agora mesmo

**Comment by afonsopacifer** [comment]
Show, vou te mandar um PR agora com um .gitignore e umas coisinhas, se quiser posso já adicionar a licença e mando tudo junto :)

**Comment by daliannyvieira** [comment]
A licença já adicionei mas me manda as outras coisas sim, por favor!

**Comment by afonsopacifer** [comment]
Rápida hahah
