### ISSUE TITLE
Translate [Transitions] session

### ISSUE THREAD

**Issue by daliannyvieira** [daliannyvieira/css-animations-pocket-guide#8]
Translate [Transitions session](https://github.com/daliannyvieira/css-animations-pocket-guide/blob/master/translations/css-animations-guia-de-bolso.md#transitions) for english on [this link](https://github.com/daliannyvieira/css-animations-pocket-guide/blob/master/translations/css-animations-pocket-guide.md#transitions).

**Comment by vihainen** [comment]
Taken!
