### ISSUE TITLE
Translate [Transforms] session

### ISSUE THREAD

**Issue by daliannyvieira** [daliannyvieira/css-animations-pocket-guide#9]
Translate [Transforms session](https://github.com/daliannyvieira/css-animations-pocket-guide/blob/master/translations/css-animations-guia-de-bolso.md#transforms) for english on [this link](https://github.com/daliannyvieira/css-animations-pocket-guide/blob/master/translations/css-animations-pocket-guide.md#transforms).

**Comment by elomar** [comment]
on it, PR soon :)

**Comment by vihainen** [comment]
Going to do this one.

**Comment by ghost** [comment]
translating
